# Generated by Django 5.0.2 on 2024-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_evenement_logement_recommandation_stage_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
