# Generated by Django 5.0.2 on 2024-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_logement_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenclub',
            name='domaine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evenclub',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='prix',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evensocial',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evensocial',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logement',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logement',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='legende',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='texte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transport',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
