# Generated by Django 5.0.2 on 2024-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_evenclub_domaine_alter_evenclub_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='prix',
        ),
        migrations.AddField(
            model_name='evenclub',
            name='prix',
            field=models.IntegerField(blank=True, default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evensocial',
            name='prix',
            field=models.IntegerField(blank=True, default=20),
            preserve_default=False,
        ),
    ]
