# Generated by Django 5.0.2 on 2024-05-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_evenclub_prix_alter_evensocial_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenclub',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='evensocial',
            name='prix',
        ),
        migrations.AlterField(
            model_name='evenclub',
            name='prixC',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='evensocial',
            name='prixS',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
