# Generated by Django 5.0.2 on 2024-05-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_remove_evenclub_prix_remove_evensocial_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
